//! DNS Linux: systemd-resolved quand il est la, `/etc/resolv.conf` sinon.

use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

use bifrost_core::config::DnsPolicy;
use bifrost_core::ports::DnsManager;
use bifrost_core::{Error, Result};

use crate::serveurs_a_interroger;

const RESOLV_CONF: &str = "/etc/resolv.conf";
const BACKUP_DIR: &str = "/var/lib/bifrost";

/// Ce qui, dans le fichier, dit qu'il est de nous.
///
/// Sert a ne PAS prendre notre propre travail pour l'etat d'origine de la
/// machine. Tailscale garde la meme garde sous le meme nom - `ownedByTailscale`
/// cherche "generated by tailscale" et `backupConfig` ne sauvegarde que si la
/// reponse est non (`net/dns/direct.go`, consulte le 20 aout 2026).
const MARQUEUR: &str = "genere par bifrost";

/// Ou l'on note la FORME du fichier d'origine, a cote de son contenu.
///
/// La sauvegarde seule ne suffit pas: elle porte le contenu, et c'est la forme
/// qui compte le plus. Un lien rendu en fichier ordinaire coupe la machine de
/// son gestionnaire de reseau pour toujours, meme a contenu identique. Or la
/// forme ne vivait qu'en memoire du daemon, donc elle mourait avec lui.
const FICHIER_ORIGINE: &str = "resolv.conf.origine";

/// Choisit l'implementation adaptee a la machine.
pub fn detect() -> Box<dyn DnsManager> {
    if resolved_is_active() {
        tracing::debug!("systemd-resolved actif, utilisation de resolvectl");
        Box::new(ResolvedDns::default())
    } else {
        tracing::debug!("systemd-resolved absent, ecriture directe de resolv.conf");
        Box::new(ResolvConfDns::default())
    }
}

/// Vrai si systemd-resolved tourne et que `resolvectl` est utilisable.
pub fn resolved_is_active() -> bool {
    if !Path::new("/run/systemd/resolve/stub-resolv.conf").exists() {
        return false;
    }
    Command::new("resolvectl")
        .arg("status")
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

/// Route tout le DNS par l'interface du tunnel via systemd-resolved.
///
/// Le point critique est le domaine `~.`: sans lui, resolved fait du split DNS
/// et interroge en parallele les resolveurs de toutes les interfaces, dont
/// celui pousse par DHCP sur l'interface physique. C'est la fuite DNS classique
/// sur Ubuntu.
#[derive(Default)]
pub struct ResolvedDns {
    applied_on: Option<String>,
}

/// Les commandes `resolvectl` qui basculent le DNS sur le tunnel.
///
/// Fonction pure, comme le ruleset nftables et le plan WFP: ce qui determine
/// s'il y a fuite DNS est verifiable en test, sans systemd-resolved ni tunnel.
pub fn resolved_apply_commands(interface: &str, policy: &DnsPolicy) -> Vec<Vec<String>> {
    let mut dns = vec!["dns".to_owned(), interface.to_owned()];
    dns.extend(serveurs_a_interroger(policy).iter().map(|a| a.to_string()));
    vec![
        dns,
        // `~.` marque ce lien comme route par defaut pour TOUTES les requetes.
        // Sans lui, resolved fait du split DNS et interroge en parallele les
        // resolveurs des autres interfaces, dont celui pousse par DHCP. C'est
        // la fuite DNS classique sur Ubuntu.
        vec!["domain".to_owned(), interface.to_owned(), "~.".to_owned()],
    ]
}

impl DnsManager for ResolvedDns {
    fn apply(&mut self, interface: &str, policy: &DnsPolicy) -> Result<()> {
        policy.validate()?;

        for args in resolved_apply_commands(interface, policy) {
            run("resolvectl", args)?;
        }
        // Les reponses mises en cache avant le tunnel viennent du resolveur du
        // FAI: les purger evite de servir des reponses hors tunnel.
        let _ = run("resolvectl", vec!["flush-caches".to_owned()]);

        self.applied_on = Some(interface.to_owned());
        tracing::info!(interface, servers = ?policy.upstream, "DNS route par le tunnel");
        Ok(())
    }

    fn restore(&mut self) -> Result<()> {
        if let Some(iface) = self.applied_on.take() {
            // `revert` remet le lien dans son etat par defaut, y compris si
            // l'interface a deja disparu (l'erreur est alors sans consequence).
            if let Err(e) = run("resolvectl", vec!["revert".to_owned(), iface.clone()]) {
                tracing::warn!(interface = %iface, error = %e, "revert DNS partiel");
            }
            let _ = run("resolvectl", vec!["flush-caches".to_owned()]);
            tracing::info!(interface = %iface, "DNS restaure");
        }
        Ok(())
    }

    fn backend(&self) -> &'static str {
        "systemd-resolved"
    }
}

/// Mode de `/etc/resolv.conf` pendant le tunnel, pose explicitement.
///
/// Non herite du umask, et ce n'est pas un detail: n'importe quel processus de
/// la machine, sous n'importe quel utilisateur, doit pouvoir lire ce fichier
/// pour resoudre un nom. Un daemon lance depuis un shell en `umask 077`
/// produirait un 600 qui casse la resolution pour tout le monde sauf root.
/// Mesure du 17/08/2026: c'est exactement ce que la recette e2e faisait sur
/// essai-linux, parce qu'elle pose `umask 077` pour proteger la cle privee du profil.
const MODE_RESOLV: u32 = 0o644;

/// Ce que `/etc/resolv.conf` etait avant que Bifrost y touche.
///
/// Rien ici n'est cosmetique. Sur une machine geree par systemd-resolved,
/// resolvconf ou NetworkManager, `/etc/resolv.conf` est un LIEN vers un fichier
/// de `/run` que le gestionnaire reecrit a chaque changement de reseau. Le
/// remplacer par un fichier ordinaire, meme avec le bon contenu, coupe ce lien
/// DEFINITIVEMENT: la machine garde ensuite les resolveurs du reseau sur lequel
/// elle se trouvait a la deconnexion, et ne les met plus jamais a jour.
///
/// L'ancienne version notait "la restauration reecrira un fichier ordinaire, ce
/// qui reste correct". Mesure du 17/08/2026 sur Ubuntu 24.04: une seule
/// execution de la recette a transforme le lien en fichier 600 root, illisible
/// par tout processus non privilegie. Le contenu etait juste; la machine
/// n'avait plus de DNS.
#[derive(Debug, Clone, PartialEq, Eq)]
enum Origine {
    /// Lien symbolique, avec sa cible telle qu'elle etait ecrite.
    Lien(PathBuf),
    /// Fichier ordinaire, avec son mode.
    Fichier(u32),
    /// Rien du tout: la restauration doit rendre l'absence.
    Absent,
    /// On a retrouve notre propre fichier SANS savoir ce qu'il a remplace.
    ///
    /// N'arrive que si la note de forme a disparu alors que le fichier, lui,
    /// est reste. Restaurer demanderait de deviner, et deviner est precisement
    /// ce qui a transforme un lien en fichier ordinaire le 17 aout 2026. On
    /// prefere le dire.
    Inconnue,
}

/// La forme, en une ligne, pour survivre a la mort du daemon.
fn ecrire_origine(chemin: &Path, origine: &Origine) -> Result<()> {
    let ligne = match origine {
        Origine::Lien(cible) => format!("lien {}\n", cible.display()),
        Origine::Fichier(mode) => format!("fichier {mode:o}\n"),
        Origine::Absent => "absent\n".to_owned(),
        // Une origine inconnue ne s'ecrit pas: la noter reviendrait a graver
        // l'ignorance et a empecher le prochain passage de faire mieux.
        Origine::Inconnue => return Ok(()),
    };
    ecrire_atomique(chemin, &ligne, 0o600)
}

/// L'inverse, tolerant: une note illisible vaut pas de note.
fn lire_origine(chemin: &Path) -> Option<Origine> {
    let texte = fs::read_to_string(chemin).ok()?;
    let ligne = texte.trim();
    if let Some(cible) = ligne.strip_prefix("lien ") {
        return Some(Origine::Lien(PathBuf::from(cible)));
    }
    if let Some(mode) = ligne.strip_prefix("fichier ") {
        return u32::from_str_radix(mode, 8).ok().map(Origine::Fichier);
    }
    (ligne == "absent").then_some(Origine::Absent)
}

/// Repli sans systemd-resolved: on sauvegarde `/etc/resolv.conf` et on ecrit
/// les resolveurs amont, joignables uniquement a travers le tunnel.
///
/// Ce mode n'utilise pas de resolveur local: les requetes partent vers l'amont
/// mais par l'interface du tunnel, donc chiffrees. Le kill switch continue de
/// dropper tout :53 qui sortirait par l'interface physique.
pub struct ResolvConfDns {
    resolv: PathBuf,
    repertoire_backup: PathBuf,
    backup: Option<PathBuf>,
    origine: Option<Origine>,
}

impl Default for ResolvConfDns {
    fn default() -> Self {
        Self::new(PathBuf::from(RESOLV_CONF), PathBuf::from(BACKUP_DIR))
    }
}

impl ResolvConfDns {
    /// Chemins injectables.
    ///
    /// Le fichier vise est le resolveur de la machine entiere: une recette qui
    /// l'eprouve en place casse le DNS de la machine qui l'execute, et c'est
    /// arrive. Avec des chemins injectables, la preservation du lien se mesure
    /// dans un repertoire jetable, sans root, sur n'importe quel runner.
    pub fn new(resolv: PathBuf, repertoire_backup: PathBuf) -> Self {
        Self {
            resolv,
            repertoire_backup,
            backup: None,
            origine: None,
        }
    }

    /// Releve la nature du chemin avant d'y toucher.
    fn relever(chemin: &Path) -> Result<Origine> {
        // `symlink_metadata` et non `metadata`: le second SUIT le lien et rend
        // un lien indiscernable d'un fichier ordinaire, ce qui est exactement
        // la distinction a conserver.
        match fs::symlink_metadata(chemin) {
            Ok(m) if m.file_type().is_symlink() => Ok(Origine::Lien(fs::read_link(chemin)?)),
            Ok(m) => Ok(Origine::Fichier(m.permissions().mode() & 0o7777)),
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(Origine::Absent),
            Err(e) => Err(e.into()),
        }
    }

    /// Le fichier en place est-il DEJA le notre.
    ///
    /// Lu par le CONTENU et non par la forme: un lien vers notre fichier reste
    /// notre fichier. `read_to_string` suit le lien, ce qui est voulu ici,
    /// contrairement a [`Self::relever`] qui doit voir le lien lui-meme.
    fn est_le_notre(chemin: &Path) -> bool {
        fs::read_to_string(chemin)
            .map(|c| c.contains(MARQUEUR))
            .unwrap_or(false)
    }

    fn fichier_origine(&self) -> PathBuf {
        self.repertoire_backup.join(FICHIER_ORIGINE)
    }
}

/// Chemin temporaire voisin de `cible`, dans le meme repertoire.
///
/// Le meme repertoire, donc le meme systeme de fichiers, donc un `rename`
/// atomique. Un temporaire dans `/tmp` obligerait a une copie, qui n'est pas
/// atomique et rouvrirait la fenetre que tout ceci sert a fermer.
fn voisin_temporaire(cible: &Path, suffixe: &str) -> PathBuf {
    let repertoire = cible.parent().unwrap_or(Path::new("/"));
    let nom = cible
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("resolv.conf");
    repertoire.join(format!(".{nom}.bifrost.{suffixe}.{}", std::process::id()))
}

/// Ecrit `contenu` a `cible` sans jamais laisser le chemin vide.
///
/// Passer par un temporaire puis renommer: `rename` est atomique, donc un
/// processus qui resout un nom pendant l'operation voit soit l'ancien fichier
/// soit le nouveau, jamais un chemin absent. Ecrire en place ouvrirait une
/// fenetre, courte mais reelle, ou la machine n'a plus de resolveur du tout.
/// Le temporaire porte aussi son mode AVANT d'etre visible.
fn ecrire_atomique(cible: &Path, contenu: &str, mode: u32) -> Result<()> {
    let temporaire = voisin_temporaire(cible, "tmp");
    let _ = fs::remove_file(&temporaire);
    fs::write(&temporaire, contenu)?;
    fs::set_permissions(&temporaire, fs::Permissions::from_mode(mode))?;
    // `rename` remplace la cible meme si c'est un lien symbolique, et c'est
    // voulu: le temps du tunnel, le fichier doit etre le notre.
    match fs::rename(&temporaire, cible) {
        Ok(()) => Ok(()),
        // Un `rename` PAR-DESSUS un point de montage echoue en EBUSY. Ce n'est
        // pas un cas theorique: Docker monte `/etc/resolv.conf` en bind dans
        // chaque conteneur. On retombe alors sur une ecriture en place, qui
        // traverse le montage et atteint le fichier reel. Elle n'est pas
        // atomique, mais l'alternative serait un Bifrost incapable de
        // configurer le DNS dans un conteneur.
        Err(e) if e.raw_os_error() == Some(libc::EBUSY) => {
            let _ = fs::remove_file(&temporaire);
            fs::write(cible, contenu)?;
            fs::set_permissions(cible, fs::Permissions::from_mode(mode))?;
            tracing::debug!(?cible, "resolv.conf monte en bind, ecriture en place");
            Ok(())
        }
        Err(e) => {
            let _ = fs::remove_file(&temporaire);
            Err(e.into())
        }
    }
}

/// Repose un lien symbolique, avec la meme atomicite que l'ecriture.
fn poser_lien_atomique(vers: &Path, lien: &Path) -> Result<()> {
    let temporaire = voisin_temporaire(lien, "lien");
    let _ = fs::remove_file(&temporaire);
    std::os::unix::fs::symlink(vers, &temporaire)?;
    if let Err(e) = fs::rename(&temporaire, lien) {
        let _ = fs::remove_file(&temporaire);
        return Err(e.into());
    }
    Ok(())
}

/// Rend son resolveur a une machine dont le daemon est mort sans restaurer.
///
/// # Pourquoi cette fonction existe
///
/// `on_shutdown` laisse DELIBEREMENT le systeme ferme: un daemon qui meurt ne
/// doit pas ouvrir les vannes. La consequence, moins voulue, est que
/// `/etc/resolv.conf` reste pointe sur un resolveur qui n'etait joignable que
/// par le tunnel. La voie de retour que le message d'arret designait,
/// `--cleanup-firewall`, ne rendait que les filtres: la machine retrouvait son
/// reseau et restait incapable de resoudre quoi que ce soit. Mesure sur
/// essai-linux le 20 aout 2026, ou le serveur du banc a cesse de resoudre le
/// site emprunte par REALITY et a fait echouer une recette qui n'avait rien a
/// voir.
///
/// # Ce qu'elle ne couvre pas, et pourquoi c'est sans gravite
///
/// Le mode systemd-resolved, lui, pose sa configuration SUR L'INTERFACE du
/// tunnel. Elle disparait avec elle, donc la machine se repare seule. Il n'y a
/// ici que le mode `/etc/resolv.conf`, le seul qui laisse une trace durable.
///
/// Rend le message a afficher, ou `None` s'il n'y avait rien a faire.
pub fn restaurer_apres_arret() -> Result<Option<String>> {
    restaurer_apres_arret_dans(ResolvConfDns::default())
}

/// Le meme travail sur des chemins injectes, pour que la recette se mesure
/// dans un repertoire jetable plutot que sur le resolveur de la machine qui
/// l'execute. Meme raison que [`ResolvConfDns::new`].
fn restaurer_apres_arret_dans(mut dns: ResolvConfDns) -> Result<Option<String>> {
    // Ne toucher qu'a NOTRE fichier. Si quelqu'un a deja remis le sien, le
    // reprendre pour le notre serait exactement l'erreur que ce chantier ferme.
    if !ResolvConfDns::est_le_notre(&dns.resolv) {
        return Ok(None);
    }
    let note = dns.fichier_origine();
    let Some(origine) = lire_origine(&note) else {
        return Err(Error::Dns(format!(
            "{} porte le resolveur du tunnel, et {} qui disait ce qu'il a remplace a disparu: l'etat d'origine doit etre remis a la main",
            dns.resolv.display(),
            note.display()
        )));
    };
    dns.origine = Some(origine.clone());
    dns.backup = Some(dns.repertoire_backup.join("resolv.conf.bak"));
    dns.restore()?;
    Ok(Some(format!(
        "resolveur restaure ({}): {:?}",
        dns.resolv.display(),
        origine
    )))
}

/// Contenu de `/etc/resolv.conf` pose pendant la duree du tunnel.
pub fn resolv_conf_contents(policy: &DnsPolicy) -> String {
    let mut content = format!("# {MARQUEUR}, restaure a la deconnexion\n");
    for s in serveurs_a_interroger(policy) {
        content.push_str(&format!("nameserver {s}\n"));
    }
    content.push_str("options edns0 trust-ad\n");
    content
}

impl DnsManager for ResolvConfDns {
    fn apply(&mut self, _interface: &str, policy: &DnsPolicy) -> Result<()> {
        policy.validate()?;

        // Le premier passage seul releve l'etat d'origine. Une reconnexion
        // rappelle `apply` sans `restore` entre les deux: relever a nouveau
        // enregistrerait le fichier de Bifrost comme etant l'original, et la
        // restauration rendrait alors les resolveurs du tunnel a une machine
        // deconnectee.
        //
        // Le champ ne protege que le meme PROCESSUS. Il ne dit rien du daemon
        // precedent, mort sans restaurer - cas normal ici, `on_shutdown` laisse
        // deliberement le systeme ferme. Au demarrage suivant, le fichier en
        // place etait le NOTRE et se faisait enregistrer comme l'original:
        // essai-linux s'est retrouve le 20 aout 2026 avec une sauvegarde contenant
        // "genere par bifrost", donc une machine a qui plus aucune
        // restauration ne pouvait rendre son resolveur. D'ou la garde par
        // marqueur, et la note de forme qui, elle, survit au processus.
        if self.origine.is_none() {
            fs::create_dir_all(&self.repertoire_backup)?;
            let backup = self.repertoire_backup.join("resolv.conf.bak");
            if Self::est_le_notre(&self.resolv) {
                match lire_origine(&self.fichier_origine()) {
                    Some(o) => {
                        tracing::info!(
                            ?o,
                            "resolv.conf etait deja le notre: origine reprise de la note laissee par le daemon precedent"
                        );
                        self.origine = Some(o);
                        self.backup = Some(backup);
                    }
                    None => {
                        tracing::error!(
                            note = %self.fichier_origine().display(),
                            "resolv.conf est le notre et la note de forme a disparu: l'etat d'origine de cette machine est perdu, la deconnexion ne le rendra pas"
                        );
                        self.origine = Some(Origine::Inconnue);
                        self.backup = None;
                    }
                }
            } else {
                let origine = Self::relever(&self.resolv)?;
                // `read_to_string` SUIT le lien: on sauvegarde le contenu
                // servi. La cible du lien, elle, est gardee dans `origine`.
                let actuel = fs::read_to_string(&self.resolv).unwrap_or_default();
                fs::write(&backup, actuel)?;
                ecrire_origine(&self.fichier_origine(), &origine)?;
                self.origine = Some(origine);
                self.backup = Some(backup);
            }
        }

        ecrire_atomique(&self.resolv, &resolv_conf_contents(policy), MODE_RESOLV)?;
        tracing::info!(servers = ?policy.upstream, "resolv.conf remplace");
        Ok(())
    }

    fn restore(&mut self) -> Result<()> {
        let Some(origine) = self.origine.take() else {
            return Ok(());
        };
        let backup = self.backup.take();

        match &origine {
            Origine::Lien(cible) => {
                // Le contenu sauvegarde n'est deliberement PAS reecrit. Il
                // appartient au gestionnaire qui possede la cible du lien, et
                // le lui imposer effacerait ce qu'il a mis a jour pendant que
                // le tunnel etait monte. Rendre le lien suffit: le gestionnaire
                // reprend la main sur un fichier dont il n'a jamais perdu le
                // controle.
                poser_lien_atomique(cible, &self.resolv)?;
            }
            Origine::Fichier(mode) => {
                let contenu = match &backup {
                    Some(b) => fs::read_to_string(b)?,
                    None => String::new(),
                };
                ecrire_atomique(&self.resolv, &contenu, *mode)?;
            }
            // Rendre un fichier la ou il n'y en avait pas laisserait a la
            // machine une configuration DNS qu'elle n'avait pas demandee.
            Origine::Absent => {
                let _ = fs::remove_file(&self.resolv);
            }
            // On ne devine pas. Poser un lien vers le stub de systemd-resolved
            // serait juste sur une Ubuntu ordinaire et faux ailleurs, et une
            // restauration fausse ne se voit pas: elle laisse une machine qui
            // resout, jusqu'au jour ou elle change de reseau.
            Origine::Inconnue => {
                tracing::error!(
                    resolv = %self.resolv.display(),
                    "etat d'origine inconnu: le resolveur du tunnel reste en place et doit etre remis a la main"
                );
            }
        }

        if let Some(b) = backup {
            let _ = fs::remove_file(&b);
        }
        let _ = fs::remove_file(self.fichier_origine());
        tracing::info!(?origine, "resolv.conf restaure");
        Ok(())
    }

    fn backend(&self) -> &'static str {
        "resolv.conf"
    }
}

fn run(program: &str, args: Vec<String>) -> Result<()> {
    let out = Command::new(program)
        .args(&args)
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .output()
        .map_err(|e| Error::Dns(format!("{program}: {e}")))?;
    if !out.status.success() {
        return Err(Error::Dns(format!(
            "{program} {}: {}",
            args.join(" "),
            String::from_utf8_lossy(&out.stderr).trim()
        )));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    // `IpAddr` n'est plus importe au niveau du module: `serveurs_a_interroger`
    // est partie dans `lib.rs` le 22/08/2026 pour etre compilee sur les DEUX
    // hotes, et l'import est reste derriere elle. Invisible depuis
    // dev-windows, ou ce fichier n'est pas compile.
    use std::net::{IpAddr, Ipv4Addr, Ipv6Addr};
    use std::sync::atomic::{AtomicU32, Ordering};

    static SUITE: AtomicU32 = AtomicU32::new(0);

    /// Repertoire jetable, sans dependance de test supplementaire.
    struct Jetable(PathBuf);

    impl Jetable {
        fn neuf() -> Self {
            let p = std::env::temp_dir().join(format!(
                "bifrost-dns-{}-{}",
                std::process::id(),
                SUITE.fetch_add(1, Ordering::Relaxed)
            ));
            let _ = fs::remove_dir_all(&p);
            fs::create_dir_all(&p).unwrap();
            Self(p)
        }

        fn resolv(&self) -> PathBuf {
            self.0.join("resolv.conf")
        }

        /// Un gestionnaire de reseau branche comme sur une vraie machine: un
        /// fichier dans un repertoire de service, et un lien vers lui.
        fn gere_par_un_service(&self, contenu: &str) -> PathBuf {
            let cible = self.0.join("run/stub-resolv.conf");
            fs::create_dir_all(cible.parent().unwrap()).unwrap();
            fs::write(&cible, contenu).unwrap();
            std::os::unix::fs::symlink("run/stub-resolv.conf", self.resolv()).unwrap();
            cible
        }

        fn gestionnaire(&self) -> ResolvConfDns {
            ResolvConfDns::new(self.resolv(), self.0.join("var"))
        }

        fn mode(&self) -> u32 {
            fs::symlink_metadata(self.resolv())
                .unwrap()
                .permissions()
                .mode()
                & 0o777
        }
    }

    impl Drop for Jetable {
        fn drop(&mut self) {
            let _ = fs::remove_dir_all(&self.0);
        }
    }

    /// Le defaut mesure le 17/08/2026: un lien remplace par un fichier
    /// ordinaire, et jamais rendu. La machine garde alors pour toujours les
    /// resolveurs du reseau sur lequel elle etait a la deconnexion.
    #[test]
    fn un_lien_symbolique_redevient_un_lien_symbolique() {
        let bac = Jetable::neuf();
        bac.gere_par_un_service("nameserver 192.168.1.1\n");
        let mut dns = bac.gestionnaire();

        dns.apply("wg0", &policy()).unwrap();
        assert!(
            !fs::symlink_metadata(bac.resolv())
                .unwrap()
                .file_type()
                .is_symlink(),
            "pendant le tunnel, le fichier doit etre celui de Bifrost"
        );

        dns.restore().unwrap();
        let apres = fs::symlink_metadata(bac.resolv()).unwrap();
        assert!(
            apres.file_type().is_symlink(),
            "le lien n'a pas ete rendu: le gestionnaire de reseau ne mettra \
             plus jamais le resolveur a jour"
        );
        assert_eq!(
            fs::read_link(bac.resolv()).unwrap(),
            PathBuf::from("run/stub-resolv.conf"),
            "le lien a ete rendu, mais vers une autre cible"
        );
    }

    /// Pendant que le tunnel est monte, le gestionnaire de reseau continue de
    /// reecrire la cible du lien. Lui reimposer le contenu sauvegarde a la
    /// connexion effacerait ce qu'il a appris entre-temps.
    #[test]
    fn la_cible_du_lien_appartient_au_gestionnaire_de_reseau() {
        let bac = Jetable::neuf();
        let cible = bac.gere_par_un_service("nameserver 192.168.1.1\n");
        let mut dns = bac.gestionnaire();

        dns.apply("wg0", &policy()).unwrap();
        fs::write(&cible, "nameserver 10.0.0.1\n").unwrap();
        dns.restore().unwrap();

        assert_eq!(
            fs::read_to_string(&cible).unwrap(),
            "nameserver 10.0.0.1\n",
            "Bifrost a ecrase la mise a jour du gestionnaire de reseau"
        );
    }

    /// Un fichier ordinaire garde son mode et son contenu.
    #[test]
    fn un_fichier_ordinaire_retrouve_son_mode_et_son_contenu() {
        let bac = Jetable::neuf();
        fs::write(bac.resolv(), "nameserver 192.168.1.1\n").unwrap();
        fs::set_permissions(bac.resolv(), fs::Permissions::from_mode(0o640)).unwrap();
        let mut dns = bac.gestionnaire();

        dns.apply("wg0", &policy()).unwrap();
        dns.restore().unwrap();

        assert_eq!(
            fs::read_to_string(bac.resolv()).unwrap(),
            "nameserver 192.168.1.1\n"
        );
        assert_eq!(bac.mode(), 0o640, "le mode d'origine n'a pas ete rendu");
    }

    /// Le mode pendant le tunnel est pose explicitement, pas herite du umask.
    ///
    /// La recette e2e tourne en `umask 077` pour proteger la cle privee du
    /// profil. Le daemon en heritait, et posait un resolv.conf en 600: tout
    /// processus non root perdait la resolution de noms.
    #[test]
    fn le_resolveur_reste_lisible_par_tout_le_monde() {
        let bac = Jetable::neuf();
        fs::write(bac.resolv(), "nameserver 192.168.1.1\n").unwrap();
        let mut dns = bac.gestionnaire();

        // SAFETY: umask ne prend qu'un masque entier et ne touche aucune memoire; on
        // restaure la valeur precedente juste apres.
        let precedent = unsafe { libc::umask(0o077) };
        let resultat = dns.apply("wg0", &policy());
        // SAFETY: umask ne prend qu'un masque entier et ne touche aucune memoire;
        // restaure la valeur precedente relevee ci-dessus.
        unsafe { libc::umask(precedent) };
        resultat.unwrap();

        assert_eq!(
            bac.mode(),
            0o644,
            "resolv.conf herite du umask: illisible hors root"
        );
    }

    /// Une reconnexion rappelle `apply` sans `restore` entre les deux.
    #[test]
    fn une_reconnexion_ne_prend_pas_le_fichier_de_bifrost_pour_l_original() {
        let bac = Jetable::neuf();
        bac.gere_par_un_service("nameserver 192.168.1.1\n");
        let mut dns = bac.gestionnaire();

        dns.apply("wg0", &policy()).unwrap();
        dns.apply("wg0", &policy()).unwrap();
        dns.restore().unwrap();

        assert!(
            fs::symlink_metadata(bac.resolv())
                .unwrap()
                .file_type()
                .is_symlink(),
            "le second apply a pris le fichier de Bifrost pour l'etat d'origine"
        );
    }

    /// Sans resolv.conf au depart, la restauration n'en invente pas un.
    #[test]
    fn l_absence_reste_l_absence() {
        let bac = Jetable::neuf();
        let mut dns = bac.gestionnaire();

        dns.apply("wg0", &policy()).unwrap();
        assert!(bac.resolv().exists(), "le tunnel doit poser un resolveur");
        dns.restore().unwrap();

        assert!(
            fs::symlink_metadata(bac.resolv()).is_err(),
            "une configuration DNS a ete laissee sur une machine qui n'en \
             avait pas"
        );
    }

    /// Le defaut mesure sur essai-linux le 20 aout 2026, et le plus couteux
    /// des trois: un daemon MORT sans restaurer, puis un autre qui demarre.
    ///
    /// La garde qui existait ne protegeait que le meme processus. Le suivant
    /// relevait le fichier de Bifrost comme etant l'original, et la sauvegarde
    /// finissait par contenir "genere par bifrost": plus aucune deconnexion,
    /// meme propre, ne pouvait alors rendre son resolveur a la machine.
    #[test]
    fn un_daemon_mort_ne_fait_pas_de_son_fichier_l_original() {
        let bac = Jetable::neuf();
        bac.gere_par_un_service("nameserver 192.168.1.1\n");

        // Le premier daemon pose le resolveur du tunnel, puis meurt: `restore`
        // n'est jamais appele, ce qui est le comportement VOULU de
        // `on_shutdown` - un daemon qui meurt laisse le systeme ferme.
        let mut premier = bac.gestionnaire();
        premier.apply("wg0", &policy()).unwrap();
        drop(premier);

        // Le suivant demarre et retrouve le fichier de son predecesseur.
        let mut second = bac.gestionnaire();
        second.apply("wg0", &policy()).unwrap();
        second.restore().unwrap();

        assert!(
            fs::symlink_metadata(bac.resolv())
                .unwrap()
                .file_type()
                .is_symlink(),
            "le daemon suivant a pris le fichier du precedent pour l'etat d'origine"
        );
    }

    /// La forme, et pas seulement le contenu: c'est elle qui devait survivre.
    #[test]
    fn la_forme_d_origine_se_relit_telle_qu_elle_a_ete_ecrite() {
        let bac = Jetable::neuf();
        let note = bac.0.join("origine");
        for origine in [
            Origine::Lien(PathBuf::from("../run/systemd/resolve/stub-resolv.conf")),
            Origine::Fichier(0o644),
            Origine::Absent,
        ] {
            ecrire_origine(&note, &origine).unwrap();
            assert_eq!(lire_origine(&note), Some(origine));
        }
        // Une note illisible ne vaut pas une forme inventee.
        fs::write(&note, "n'importe quoi\n").unwrap();
        assert_eq!(lire_origine(&note), None);
    }

    /// Notre fichier sans sa note: on ne devine pas, et on le DIT.
    #[test]
    fn sans_note_de_forme_l_origine_n_est_pas_devinee() {
        let bac = Jetable::neuf();
        bac.gere_par_un_service("nameserver 192.168.1.1\n");
        let mut premier = bac.gestionnaire();
        premier.apply("wg0", &policy()).unwrap();
        drop(premier);
        // La note disparait, le fichier reste.
        fs::remove_file(bac.0.join("var").join(FICHIER_ORIGINE)).unwrap();

        let mut second = bac.gestionnaire();
        second.apply("wg0", &policy()).unwrap();
        second.restore().unwrap();

        // Rien n'a ete invente: surtout pas un lien vers une cible plausible.
        assert!(
            ResolvConfDns::est_le_notre(&bac.resolv()),
            "une origine a ete devinee la ou elle etait perdue"
        );
    }

    /// Le retour en arriere apres un daemon mort, qui est ce que
    /// `--cleanup-firewall` fait desormais en plus des filtres.
    #[test]
    fn le_nettoyage_rend_son_resolveur_a_la_machine() {
        let bac = Jetable::neuf();
        bac.gere_par_un_service("nameserver 192.168.1.1\n");
        let mut daemon = bac.gestionnaire();
        daemon.apply("wg0", &policy()).unwrap();
        drop(daemon);

        let dit = restaurer_apres_arret_dans(bac.gestionnaire()).unwrap();

        assert!(dit.is_some(), "le nettoyage n'a rien dit avoir fait");
        assert!(
            fs::symlink_metadata(bac.resolv())
                .unwrap()
                .file_type()
                .is_symlink(),
            "le nettoyage a laisse le resolveur du tunnel en place"
        );
        // Deux fois de suite: la seconde ne doit plus rien trouver a faire,
        // et surtout ne pas defaire ce que le gestionnaire de reseau a repris.
        assert_eq!(
            restaurer_apres_arret_dans(bac.gestionnaire()).unwrap(),
            None
        );
    }

    /// Le temoin negatif du precedent: un fichier qui n'est pas de nous ne se
    /// fait pas "restaurer" par un nettoyage.
    #[test]
    fn le_nettoyage_ne_touche_pas_au_fichier_d_un_autre() {
        let bac = Jetable::neuf();
        fs::write(bac.resolv(), "nameserver 9.9.9.9\n").unwrap();

        assert_eq!(
            restaurer_apres_arret_dans(bac.gestionnaire()).unwrap(),
            None
        );
        assert_eq!(
            fs::read_to_string(bac.resolv()).unwrap(),
            "nameserver 9.9.9.9\n"
        );
    }

    /// `restore` sans `apply` prealable ne doit rien toucher.
    #[test]
    fn restaurer_sans_avoir_applique_ne_touche_a_rien() {
        let bac = Jetable::neuf();
        fs::write(bac.resolv(), "nameserver 192.168.1.1\n").unwrap();

        bac.gestionnaire().restore().unwrap();

        assert_eq!(
            fs::read_to_string(bac.resolv()).unwrap(),
            "nameserver 192.168.1.1\n"
        );
    }

    fn policy() -> DnsPolicy {
        DnsPolicy {
            local_resolver: IpAddr::V4(Ipv4Addr::new(127, 0, 0, 53)),
            upstream: vec![
                IpAddr::V4(Ipv4Addr::new(10, 2, 0, 1)),
                IpAddr::V6(Ipv6Addr::new(0xfd00, 0, 0, 0, 0, 0, 0, 1)),
            ],
            embarque: false,
            anti_telemetrie: bifrost_core::config::ProfilTelemetrie::Aucun,
        }
    }

    fn lignes(cmds: &[Vec<String>]) -> Vec<String> {
        cmds.iter().map(|c| c.join(" ")).collect()
    }

    #[test]
    fn les_resolveurs_amont_sont_poses_sur_l_interface_du_tunnel() {
        let l = lignes(&resolved_apply_commands("wg0", &policy()));
        assert_eq!(l[0], "dns wg0 10.2.0.1 fd00::1");
    }

    /// Sans le domaine `~.`, systemd-resolved interroge en parallele les
    /// resolveurs des autres interfaces, dont celui pousse par DHCP. C'est la
    /// fuite DNS la plus courante sur Ubuntu.
    #[test]
    fn le_domaine_route_only_est_pose() {
        let l = lignes(&resolved_apply_commands("wg0", &policy()));
        assert!(
            l.iter().any(|c| c == "domain wg0 ~."),
            "domaine '~.' absent: {l:?}"
        );
    }

    #[test]
    fn le_nom_de_l_interface_est_repris_partout() {
        let l = lignes(&resolved_apply_commands("bifrost0", &policy()));
        assert!(l.iter().all(|c| c.contains("bifrost0")));
    }

    #[test]
    fn resolv_conf_ne_liste_que_les_resolveurs_amont() {
        let c = resolv_conf_contents(&policy());
        assert!(c.contains("nameserver 10.2.0.1"));
        assert!(c.contains("nameserver fd00::1"));
        assert_eq!(c.matches("nameserver").count(), 2);
    }

    /// Sans resolveur embarque, le loopback ne doit pas atterrir dans
    /// resolv.conf: rien n'y ecoute, la resolution serait simplement cassee.
    #[test]
    fn resolv_conf_ne_pointe_pas_le_resolveur_local() {
        let c = resolv_conf_contents(&policy());
        assert!(!c.contains("127.0.0.53"));
    }

    /// Avec resolveur embarque, l'exact inverse: c'est LUI qu'il faut
    /// interroger. Le condition de la regle precedente n'etait pas "loopback",
    /// c'etait "rien n'ecoute".
    #[test]
    fn resolv_conf_pointe_le_resolveur_embarque_quand_il_y_en_a_un() {
        let c = resolv_conf_contents(&DnsPolicy {
            embarque: true,
            anti_telemetrie: bifrost_core::config::ProfilTelemetrie::Aucun,
            ..policy()
        });
        assert!(c.contains("nameserver 127.0.0.53"), "{c}");
    }

    /// Le defaut qui annulerait tout le composant: laisser les amonts en
    /// secours a cote du resolveur chiffre. Au premier hoquet de celui-ci, le
    /// systeme basculerait sur une resolution en clair sans rien dire, et
    /// justement le jour ou le chiffrement servait.
    #[test]
    fn le_resolveur_embarque_n_a_aucun_secours_en_clair() {
        let c = resolv_conf_contents(&DnsPolicy {
            embarque: true,
            anti_telemetrie: bifrost_core::config::ProfilTelemetrie::Aucun,
            ..policy()
        });
        assert_eq!(
            c.matches("nameserver").count(),
            1,
            "un resolveur de secours accompagne le resolveur chiffre\n{c}"
        );
        for amont in &policy().upstream {
            assert!(
                !c.contains(&amont.to_string()),
                "l'amont {amont} reste joignable en clair\n{c}"
            );
        }
    }

    /// Les deux backends doivent designer le meme serveur. Diverger donnerait
    /// un produit dont le comportement depend de la presence de
    /// systemd-resolved sur la machine.
    #[test]
    fn les_deux_backends_designent_le_meme_serveur() {
        let p = DnsPolicy {
            embarque: true,
            anti_telemetrie: bifrost_core::config::ProfilTelemetrie::Aucun,
            ..policy()
        };
        let l = lignes(&resolved_apply_commands("wg0", &p));
        assert_eq!(l[0], "dns wg0 127.0.0.53");
        assert!(resolv_conf_contents(&p).contains("nameserver 127.0.0.53"));
    }

    #[test]
    fn resolv_conf_est_identifiable_comme_genere() {
        assert!(resolv_conf_contents(&policy()).starts_with("# genere par bifrost"));
    }
}
